//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class typing:public drogon::DrTemplate<typing>
{
public:
	typing(){};
	virtual ~typing(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
